---
    - name: Ensure SSL directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      with_items:
        - /etc/pki/tls/private
        - /etc/pki/tls/certs

    - name: Check if SSL key exists
      stat:
        path: /etc/pki/tls/private/self_signed.key
      register: ssl_key_stat

    - name: Check if SSL certificate exists
      stat:
        path: /etc/pki/tls/certs/self_signed.crt
      register: ssl_crt_stat

    - name: Generate self-signed SSL certificate if cert and key don't exist
      command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/pki/tls/private/self_signed.key -out /etc/pki/tls/certs/self_signed.crt -subj "/C=US/ST=State/L=City/O=Organization/OU=OrgUnit/CN=localhost"
      when: not (ssl_key_stat.stat.exists and ssl_crt_stat.stat.exists)

    - name: Output a message if the SSL certificate and key already exist
      debug:
        msg: "SSL certificate and key already exist; skipping generation."
      when: ssl_key_stat.stat.exists and ssl_crt_stat.stat.exists

    - name: Activer le module SSL d'Apache
      ansible.builtin.command: a2enmod ssl
      notify:
        - Restart Apache

    - name: Créer un VirtualHost pour HTTPS
      ansible.builtin.blockinfile:
        path: /etc/apache2/sites-available/zabbix-ssl.conf
        create: yes
        block: |
          <VirtualHost *:443>
              ServerAdmin webmaster@localhost
              DocumentRoot /usr/share/zabbix
              
              SSLEngine on
              SSLCertificateFile /etc/pki/tls/certs/self_signed.crt
              SSLCertificateKeyFile /etc/pki/tls/private/self_signed.key

              <Directory "/usr/share/zabbix">
                  Options FollowSymLinks
                  AllowOverride None
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
      notify:
        - Enable SSL Site

    - name: Configure HTTP to HTTPS redirection in Apache
      blockinfile:
        path: /etc/apache2/sites-available/000-default.conf
        block: |
          <VirtualHost *:80>
              ServerName X.X.X.X
              Redirect permanent / https://X.X.X.X/
          </VirtualHost>
        marker: "# HTTP TO HTTPS REDIRECTION"
      notify:
        - Restart Apache

    - name: Activer le site SSL dans Apache
      ansible.builtin.command: a2ensite zabbix-ssl.conf
      notify:
        - Restart Apache
